root: true
env:
    node: true
    jquery: true
    browser: true
extends:
    - plugin:vue/recommended
    - "@vue/prettier"
    - "@vue/typescript"
    - "@vue/prettier/@typescript-eslint"
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:import/typescript
rules:
    no-console: 0
    no-debugger: 2
    prefer-const: 1
    vue/require-default-prop: 0
    no-var: 2
    vue/no-v-html: 0
    no-constant-condition: 0
    "@typescript-eslint/explicit-member-accessibility": 0
    "@typescript-eslint/no-explicit-any": 0
    "@typescript-eslint/no-non-null-assertion": 0
    "@typescript-eslint/no-use-before-define": 0
    "@typescript-eslint/no-object-literal-type-assertion": 0
    "@typescript-eslint/camelcase": 0
    "@typescript-eslint/no-parameter-properties": 0
parserOptions:
    parser: "@typescript-eslint/parser"
settings:
    import/parsers:
        "@typescript-eslint/parser": [".ts", ".tsx"]
    import/resolver:
        "typescript": {} # use <root>/tsconfig.json
