language: node_js
node_js:
    - stable

script: bash ./deploy.sh

before_install:
    - openssl aes-256-cbc -K $encrypted_60d7449a1baf_key -iv $encrypted_60d7449a1baf_iv
      -in deploy_key.enc -out ./deploy_key -d
