language: node_js
node_js:
    - stable
script: bash ./deploy.sh
env:
    global:
        - ENCRYPTION_LABEL: '60d7449a1baf'
        - COMMIT_AUTHOR_EMAIL: '21034047+hanzhi713@users.noreply.github.com'
install:
    - npm install
    - npm install codecov -g
after_success:
    - codecov
# before_install:
# - openssl aes-256-cbc -K $encrypted_60d7449a1baf_key -iv $encrypted_60d7449a1baf_iv
#   -in deploy_key.enc -out ./deploy_key -d
