language: node_js
node_js:
    - 14
install:
    - npm install -g codecov
    - npm ci

cache:
    directories:
        - node_modules
        - $HOME/.cache/electron
        - $HOME/.cache/electron-builder

env:
    global:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - ENCRYPTION_LABEL=60d7449a1baf
        - COMMIT_AUTHOR_EMAIL="21034047+hanzhi713@users.noreply.github.com"

jobs:
    include:
        - stage: Build and Deploy
          os: linux
          dist: xenial
          addons:
              snaps:
                  - name: snapcraft
                    confinement: classic
          script:
              - bash ./scripts/deploy.sh # tests run here
              - npx electron-builder --linux
          after_success:
              - codecov
        - stage: Build and Deploy
          os: osx
          osx_image: xcode10.2
          script:
              - npm run getwasm
              - npm run build
              - npx electron-builder --mac
        - stage: Build and Deploy
          os: windows
          script:
              - ./scripts/get_wasm.sh # cannot use npm run getwasm here because it will use window's command prompt
              - npm run build
              - npx electron-builder --win
